import os, sys, subprocess, time, re, torch
os.environ.setdefault("PJRT_DEVICE", "CPU")
import torch_xla
dev = torch_xla.device()
OUT = "/opt/hyt/isgv"
FLAGS = ["--target=trn2", "--model-type=transformer", "--optlevel=1", "--enable-saturate-infinity", "--lnc=2", "--verbose=35"]
NT, S, D, NF = 4096, 64, 10, 32768
NBUF = 59965460

def compile_outs(name, outs):
    pb = torch_xla._XLAC._get_xla_tensors_hlo_proto(outs)
    pbf = f"{OUT}/p10_{name}.hlo.pb"; open(pbf, "wb").write(pb)
    t0 = time.time()
    r = subprocess.run(["neuronx-cc", "compile", "--framework=XLA", pbf, "--output", pbf.replace(".hlo.pb", ".neff")] + FLAGS, capture_output=True, text=True, timeout=3600)
    o = r.stdout + r.stderr
    m = re.search(r"Instructions generated by compiler (\d+)", o)
    tag = "OK" if r.returncode == 0 else ("EXTP003 instr=" + m.group(1) if m else "FAIL: " + o[-300:].replace("\n", " | "))
    print(f"[{name}] {tag} in {time.time()-t0:.0f}s", flush=True)

def bucket_copy(grad_list):
    buf = torch.zeros(NBUF, dtype=torch.bfloat16, device=dev)
    off = 0
    for g in grad_list:
        n = g.numel(); buf[off:off + n].copy_(g.reshape(-1).to(torch.bfloat16)); off += n
    return buf

which = sys.argv[1]
torch.manual_seed(0)
if which == "cb_bucket":            # codebook grad [32768,10] accumulated ~40x then flat-copied into the bucket
    acc = torch.zeros(NF, D, device=dev)
    torch_xla.sync()
    for _ in range(40):
        acc = acc + torch.randn(NF, D, device=dev)
    buf = bucket_copy([torch.randn(640, 640, device=dev), acc, torch.randn(640, 2560, device=dev)])
    compile_outs("cb_bucket", [buf])
if which == "cb_bucket_flat":       # same but the codebook grad lives flat [327680] and is viewed as [32768,10]
    acc = torch.zeros(NF * D, device=dev)
    torch_xla.sync()
    for _ in range(40):
        acc = acc + torch.randn(NF * D, device=dev)
    buf = bucket_copy([torch.randn(640, 640, device=dev), acc.view(NF, D), torch.randn(640, 2560, device=dev)])
    compile_outs("cb_bucket_flat", [buf])
if which == "where_sd":             # fixed-shape host apply as shipped: where on [nt,S,d] + its backward select
    h = torch.randn(NT, S * D, device=dev, requires_grad=True)
    torch_xla.sync()
    outs = []
    x = h
    for _ in range(20):
        mask = (torch.randint(0, 10, (NT, S, 1), device=dev) == 0)
        new = torch.randn(NT, S, D, device=dev)
        x = torch.where(mask, new, x.reshape(NT, S, D)).reshape(NT, S * D)
        x = x * 1.01
    x.sum().backward()
    compile_outs("where_sd", [x, h.grad])
if which == "where_flat":           # same apply but mask/new expanded on host to [nt, D]
    h = torch.randn(NT, S * D, device=dev, requires_grad=True)
    torch_xla.sync()
    x = h
    for _ in range(20):
        mask = (torch.randint(0, 10, (NT, S * D), device=dev) == 0)
        new = torch.randn(NT, S * D, device=dev)
        x = torch.where(mask, new, x)
        x = x * 1.01
    x.sum().backward()
    compile_outs("where_flat", [x, h.grad])
def P(*shape, dtype=torch.float32):
    t = torch.randn(*shape) if dtype.is_floating_point else (torch.randint(0, 10, shape) == 0)
    return t.to(dtype).to(dev) if dtype.is_floating_point else t.to(dev)
if which == "param_where_sd":       # as shipped: host uploads new_dev f32[nt,S,d] and mask pred[nt,S,1] per unit
    h = torch.randn(NT, S * D).to(dev).requires_grad_(True)
    x = h
    for _ in range(20):
        mask = P(NT, S, 1, dtype=torch.bool); new = P(NT, S, D)
        x = torch.where(mask, new, x.reshape(NT, S, D)).reshape(NT, S * D) * 1.01
    x.sum().backward(); compile_outs("param_where_sd", [x, h.grad])
if which == "param_where_flat":     # host expands mask/new to [nt, D] before upload
    h = torch.randn(NT, S * D).to(dev).requires_grad_(True)
    x = h
    for _ in range(20):
        mask = P(NT, S * D, dtype=torch.bool); new = P(NT, S * D)
        x = torch.where(mask, new, x) * 1.01
    x.sum().backward(); compile_outs("param_where_flat", [x, h.grad])
if which == "param_cb":             # 40 host-uploaded codebook grads f32[32768,10] accumulated, into the bucket
    acc = P(NF, D)
    for _ in range(39): acc = acc + P(NF, D)
    compile_outs("param_cb", [bucket_copy([P(640, 640), acc, P(640, 2560)])])
if which == "param_cb_flat":        # host uploads flat [327680]; viewed as [32768,10] only for the parameter
    acc = P(NF * D)
    for _ in range(39): acc = acc + P(NF * D)
    compile_outs("param_cb_flat", [bucket_copy([P(640, 640), acc.view(NF, D), P(640, 2560)])])
if which == "optim_cb":            # AdamW-style update of the [32768,10] codebook from a host-uploaded grad, plus grad norm
    cb = P(NF, D); g = P(NF, D); m = P(NF, D); v = P(NF, D)
    f = lambda x: torch.tensor(x, dtype=torch.float32).to(dev)
    lr, b1, b2, eps, wd, thr, ini = f(0.01), f(0.9), f(0.95), f(1e-8), f(0.1), f(0.0039), f(0.01)
    m2 = m * b1 + g * (f(1.0) - b1); v2 = v * b2 + (g * g) * (f(1.0) - b2)
    cb2 = cb - lr * (m2 / (v2.sqrt() + eps)) - lr * wd * cb
    gn = g.norm()
    cbn = cb2.square().sum(dim=1, keepdim=True).sqrt()
    cb3 = torch.where(cbn < thr, torch.zeros_like(cb2) + ini, cb2)   # renorm_or_reset-like
    compile_outs("optim_cb", [cb3, m2, v2, gn])
